routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['middleware' => 'auth.administrators'], function () {
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');
        Route::resource('/user/administrator', 'Admin\AdminController');
        Route::resource('/user/partner', 'Admin\PartnerController');
        // Route::post('/user/partner/{id}/destroy', 'Admin\PartnerController@destroy')->name('destroy_partner');

        Route::resource('/vacancy', 'Admin\VacancyController');

        Route::get('/vacancy/{id}/applies', 'Admin\VacancyController@applies')->name('vacancy.applies.index');
        Route::get('/vacancy/{id}/applies/{apply_id}', 'Admin\VacancyController@applies_action')->name('vacancy.applies.action');

        Route::get('/vacancy/{id}/interview', 'Admin\InterviewController@interview')->name('interview');
        Route::post('/store_interview', 'Admin\InterviewController@store_interview')->name('store_interview');

        Route::get('/vacancy/{id}/submit_interview', 'Admin\InterviewController@submit_interview')->name('submit_interview');
        Route::post('/store_submit_interview', 'Admin\InterviewController@store_submit_interview')->name('store_submit_interview');

        Route::resource('/announcement', 'Admin\AnnouncementController');

        Route::resource('/activity', 'Admin\ActivityController');


        Route::resource('/setting', 'Admin\SettingController');
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
            Route::get('/about_us/edit/{id}', 'Admin\SettingController@edit_about_us')->name('edit_about_us');
            Route::post('/about_us/update_about_us/{id}', 'Admin\SettingController@update_about_us')->name('update_about_us');
            Route::get('/about_us/add_about_us', 'Admin\SettingController@create_about_us')->name('create_about_us');
            Route::post('/about_us/store_about_us', 'Admin\SettingController@store_about_us')->name('store_about_us');
        });

        Route::resource('/position', 'Admin\PositionController');
        Route::get('/position/detail/{id}', 'Admin\PositionController@detail_posisi')->name('detail_position');
    });

    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout');
});


Route::get('/pusher', function () {
    return view('welcome2');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

// Login

Route::get('/login', 'Auth\LoginController@login_partner')->name('login.index');
Route::get('/register', 'Auth\RegisterController@register_partner')->name('register.index');
Route::post('/register', 'Auth\RegisterController@register_partner_store')->name('register.store');
Route::get('/logout', 'Auth\LoginController@logout_partner')->name('logout');

Route::post('/upload', 'UploadController@upload')->name('upload');

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/vacancy', 'HomeController@vacancy')->name('vacancy');
    Route::get('/vacancy/{id}', 'HomeController@vacancy_detail')->name('vacancy.detail');
    Route::post('/vacancy/{id}/apply', 'HomeController@vacancy_apply')->name('vacancy.apply');
    Route::get('/announcement', 'HomeController@announcement')->name('announcement');
    Route::get('/announcement/{id}', 'HomeController@announcement_detail')->name('announcement.detail');
    Route::get('/activity', 'HomeController@activity')->name('activity');

    //profile

    Route::get('/account/profile', 'HomeController@profile')->name('profile');
    Route::post('/account/profile', 'HomeController@profile_update')->name('profile.update');

    Route::get('/account/applies', 'HomeController@applies')->name('applies');
    Route::get('/account/applies/{id}/detail', 'HomeController@applies_detail')->name('applies_detail');
    Route::get('/account/applies/{id}/cancel', 'HomeController@applies_cancel')->name('applies.cancel');
});

// Route::get('test_admin', function () {
//     event(new App\Events\NotifAdmin('Lolosneee', 'Didik Ariyana', '1605365067.png', '2020-12-02 19:34:16'));
//     return "Event has been sent!";
// });

resources/views/announcement-detail.blade.php
@extends('layouts.home-app')
@section('title')
    {{ $data->title }}
@endsection
@section('content')


    <div class="site-section bg-light pb-0" style="padding-top:250px;">
        <div class="container">
            <div class="row mb-5 justify-content-center text-center">
                <div class="col-lg-4">
                    <span class="caption">Pengumuman</span>
                    <h2 class="title-with-line text-center mb-5">{{ $data->title }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <img src="{{ asset('/uploads/announcement/' . $data->photo) }}" alt="Image" class="img-fluid"
                        width="250">
                </div>
                <div class="col-md-12 mt-5 mb-5">
                    {!! $data->description !!}
                </div>
            </div>
        </div>
    </div>


    <div class="site-section ftco-subscribe-1" style="background-image: url('{{ asset('home/images/hero_2.jpg') }}')">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <h2>Tunggu Apalagi?</h2>
                    <p>Saatnya sekarang juga anda bergabung menjadi mitra kami.</p>
                </div>
                <div class="col-lg-5 d-flex justify-content-end">
                    <button class="btn btn-outline-light rounded py-3 px-4" type="submit">Bergabung Menjadi Mitra</button>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/announcement.blade.php
@extends('layouts.home-app')

@section('title')
    Pengumuman
@endsection

@section('content')

    <style>
        .foto-responsive {
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
            padding-bottom: 80%;
            min-width: 100%;
        }

    </style>

    <div class="site-section bg-light pb-0" style="padding-top:250px;">
        <div class="container">
            <div class="row mb-5 justify-content-center text-center">
                <div class="col-lg-4">
                    <span class="caption">Pengumuman</span>
                    <h2 class="title-with-line text-center mb-5">Pengumuman Terbaru Dari Kami</h2>
                </div>
            </div>
            <div class="row mb-5">
                @if (count($announcements) > 0)
                    @foreach ($announcements as $announcement)
                        <div class="col-lg-4">
                            <div class="news-entry-item">
                                <a href="{{ route('home.announcement.detail', $announcement->id) }}" class="thumbnail">
                                    {{-- <img src="{{ $announcement->photo }}" alt="Image"
                                        class="img-fluid"> --}}
                                    {{-- <img
                                        src="{{ asset('/uploads/announcement/' . $announcement->photo) }}" alt="Image"
                                        class="img-fluid"> --}}

                                    <div class="box-img foto-responsive card-img-top"
                                        style="
                                                                        background-image: url(
                                                                        {{ asset('/uploads/announcement/' . $announcement->photo) }} );">
                                    </div>
                                    <div class="date">
                                        <span>{{ date('d', strtotime($announcement->created_at)) }}</span>
                                        <span>{{ date('F', strtotime($announcement->created_at)) }}</span>
                                    </div>
                                </a>
                                <h3 class="mb-0"><a href="#">{{ $announcement->title }}</a></h3>
                                <div class="mb-3">
                                    by <b>{{ $announcement->administrator->name ?? '-' }}</b>
                                </div>
                                <p align="justify">
                                    {{ substr(strip_tags($announcement->description), 0, 200) }}..
                                </p>
                            </div>
                        </div>
                    @endforeach
                @else

                    <div class="col-lg-12 text-center">
                        <p>Tidak ada pengumuman untuk saat ini</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
    @guest
        <div class="site-section ftco-subscribe-1" style="background-image: url('{{ asset('home/images/hero_2.jpg') }}')">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <h2>Tunggu Apalagi?</h2>
                        <p>Saatnya sekarang juga anda bergabung menjadi mitra kami.</p>
                    </div>
                    <div class="col-lg-5 d-flex justify-content-end">
                        <a href="/register" class="btn btn-outline-light rounded py-3 px-4" type="submit">Bergabung Menjadi
                            Mitra</a>
                    </div>
                </div>
            </div>
        </div>
    @endguest


@endsection

resources/views/applies.blade.php
@extends('layouts.home-app')
@section('title')
    Lamaran Saya
@endsection
@section('content')


    <div class="site-section bg-light pb-0" style="padding-top:250px;">
        <div class="container">
            <div class="row mb-5 justify-content-center text-center">
                <div class="col-lg-4">
                    <span class="caption">Lamaran Saya</span> <br><br>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 mb-5">
                    <div class="card">
                        <div class="card-header">
                            Data Lamaran saya
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="datatable" class="table table-striped" style="width: 100%">
                                        <thead>
                                            <tr>
                                                <th>Nama Lowongan</th>
                                                <th>Posisi</th>
                                                <th>Tanggal Melamar</th>
                                                <th>Status</th>
                                                <th>Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (isset($data))
                                                @foreach ($data as $apply)
                                                    <tr>
                                                        <td>
                                                            <a
                                                                href="{{ route('home.vacancy.detail', $apply->vacancy_id) }}">
                                                                {{ $apply->vacancy->title }}
                                                            </a>
                                                        </td>
                                                        <td>
                                                            <span
                                                                class="badge badge-primary">{{ $apply->position->name }}</span>
                                                        </td>
                                                        <td>{{ date('d F Y - H:i', strtotime($apply->created_at)) }}</td>
                                                        <td>
                                                            @if ($apply->status == 'UNAPPROVED')
                                                                <span class="badge badge-warning text-white">Belum
                                                                    Disetujui</span>
                                                            @elseif($apply->status == "APPROVED")
                                                                <span
                                                                    class="badge badge-success text-white">Disetujui</span>
                                                            @elseif($apply->status == "INTERVIEW")
                                                                <span class="badge badge-info text-white">Interview</span>
                                                            @else
                                                                <span class="badge badge-danger">Ditolak</span>
                                                            @endif
                                                        </td>
                                                        <td>
                                                            @if ($apply->status == 'UNAPPROVED')
                                                                <a href="{{ route('home.applies.cancel', $apply->id) }}">
                                                                    <button type="button"
                                                                        class="btn btn-sm btn-danger">Batalkan</button>
                                                                </a>
                                                            @elseif ($apply->status == 'INTERVIEW')
                                                                <button type="button" class="btn btn-sm btn-danger"
                                                                    disabled>Batalkan</button>
                                                            @elseif ($apply->status == 'REJECTED')
                                                                <a href="{{ url('/account/applies/' . $apply->id) }}/detail"
                                                                    class="btn btn-sm btn-danger">Detail</a>
                                                            @else
                                                                <a href="{{ url('/account/applies/' . $apply->id) }}/detail"
                                                                    class="btn btn-sm btn-success"
                                                                    style="color: white">Detail</a>
                                                            @endif
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            @else
                                                <p>belum ada data</p>
                                            @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @guest

        <div class="site-section ftco-subscribe-1" style="background-image: url('{{ asset('home/images/hero_2.jpg') }}')">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <h2>Tunggu Apalagi?</h2>
                        <p>Saatnya sekarang juga anda bergabung menjadi mitra kami.</p>
                    </div>
                    <div class="col-lg-5 d-flex justify-content-end">
                        <a href="/register" class="btn btn-outline-light rounded py-3 px-4" type="submit">Bergabung Menjadi
                            Mitra</a>
                    </div>
                </div>
            </div>
        </div>
    @endguest



@endsection

resources/views/home.blade.php
@extends('layouts.home-app')

@section('title')
    Beranda
@endsection

@section('hero')
    @include('components.hero')
@endsection

@section('content')

    <div class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-4 mb-lg-0">
                    <img src="{{ url($about->photo) }}" alt="Image" class="img-fluid">
                </div>
                <div class="col-lg-5 ml-auto">
                    <span class="caption">Tentang Kami</span>
                    <h2 class="title-with-line">{{ $about->title ?? '-' }}</h2>


                    <p class="mb-4">
                        {{ $about->description_short ?? '-' }}
                    </p>

                    <a href="{{ route('home.about') }}">
                        <button class="btn btn-outline-primary">Lihat Selengkapnya</button>
                    </a>


                </div>
            </div>
        </div>
    </div>

    <div class="site-section pt-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 text-center">
                    <div class="numbers">
                        <strong class="d-block">{{ $count_partner }}</strong>
                        <span>Jumlah Mitra</span>
                    </div>
                </div>
                <div class="col-lg-6 text-center">
                    <div class="numbers">
                        <strong class="d-block">{{ $count_vacancy }}</strong>
                        <span>Jumlah Lowongan</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section bg-light pb-0">
        <div class="container">
            <div class="row mb-5 justify-content-center text-center">
                <div class="col-lg-4">
                    <span class="caption">Lowongan</span>
                    <h2 class="title-with-line text-center mb-5">Ayo ikuti lowongan yang tersedia dari kami</h2>
                </div>
            </div>
            <div class="row">
                @if (count($vacancies) > 0)

                    @foreach ($vacancies as $vacancy)

                        @if (Carbon\Carbon::now()->format('Y-m-d h:m:s') < $vacancy->end_period)

                            <div class="col-lg-4 col-md-6">
                                <div class="feature-1">
                                    <div class="feature-1-content">
                                        <img src="{{ asset('/uploads/vacancy/' . $vacancy->photo) }}" class="mb-5" alt=""
                                            width="100%">
                                        <h2>{{ $vacancy->title }}</h2>
                                        <p align="justify">{{ substr(strip_tags($vacancy->description), 0, 200) }}..</p>
                                        <p><a href="{{ route('home.vacancy.detail', $vacancy->id) }}"
                                                class="btn btn-outline-primary px-4 ">Lihat Selengkapnya</a></p>
                                        <hr>
                                        <table>
                                            <tr>
                                                <td align="left">Berakhir Pada</td>
                                                <td align="left">:</td>
                                                <td align="left">
                                                    <span class="badge badge-primary">
                                                        {{ date('d F Y', strtotime($vacancy->end_period)) }}
                                                    </span>
                                                </td>
                                            </tr>
                                            @foreach ($vacancy->detail as $detail)
                                                <tr>
                                                    <td align="left">Posisi {{ $detail->position->name }}</td>
                                                    <td align="left">:</td>
                                                    <td align="left">
                                                        <span class="badge badge-success text-white">
                                                            Diperlukan {{ $detail->max_partner }}, Tersedia
                                                            {{ $detail->max_partner - $detail->current_partner }},
                                                            Terisi
                                                            {{ $detail->max_partner }}
                                                        </span>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </table>
                                    </div>
                                </div>
                            </div>
                        @endif
                    @endforeach

                    <div class="col-lg-12 mb-5 d-flex justify-content-end">
                        <a href="{{ route('home.vacancy') }}">
                            <button class="btn btn-primary">Lihat Lebih Banyak</button>
                        </a>
                    </div>

                @else
                    <div class="col-lg-12 text-center">
                        <p>Tidak ada lowongan untuk saat ini</p>
                    </div>
                @endif
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row mb-5 justify-content-center text-center">
                <div class="col-lg-4">
                    <span class="caption">Info Kegiatan</span>
                    <h2 class="title-with-line text-center mb-5">Info Kegiatan Kami</h2>
                </div>
            </div>
            <div class="row">
                @if (count($activities) > 0)

                    <section class="gallery-block cards-gallery">
                        <div class="container">
                            <div class="row">
                                @foreach ($activities as $activity)
                                    <div class="col-md-6 col-lg-4">
                                        <div class="card border-0 transform-on-hover">
                                            <a class="lightbox" href="{{ asset('/uploads/activity/' . $activity->photo) }}">
                                                <img src="{{ asset('/uploads/activity/' . $activity->photo) }}" alt="<h3>{{ $activity->title }}</h3>{{ $activity->description }}
                                                                                                  " class="card-img-top">
                                            </a>
                                            <div class="card-body">
                                                <h6><a href="#">{{ $activity->title }}</a></h6>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach

                                <div class="col-lg-12 mb-5 d-flex justify-content-end">
                                    <a href="{{ route('home.activity') }}">
                                        <button class="btn btn-primary">Lihat Lebih Banyak</button>
                                    </a>
                                </div>


                            </div>
                        </div>
                    </section>
                @else
                    <div class="col-lg-12 text-center">
                        <p>Tidak ada info kegiatan untuk saat ini</p>
                    </div>
                @endif
            </div>
        </div>
    </div>




    <div class="site-section">
        <div class="container">

            <div class="row">
                <div class="col-lg-4 mb-5">
                    <span class="caption">Pengumuman</span>
                    <h2 class="title-with-line mb-2">Pengumuman Terbaru Dari Kami</h2>
                </div>
            </div>

            <div class="row">
                @if (count($announcements) > 0)
                    @foreach ($announcements as $announcement)
                        <div class="col-lg-4">
                            <div class="news-entry-item">
                                <a href="{{ route('home.announcement.detail', $announcement->id) }}" class="thumbnail">
                                    <img src="{{ asset('/uploads/announcement/' . $announcement->photo) }}" alt="Image"
                                        class="img-fluid">
                                    <div class="date">
                                        <span>{{ date('d', strtotime($announcement->created_at)) }}</span>
                                        <span>{{ date('F', strtotime($announcement->created_at)) }}</span>
                                    </div>
                                </a>
                                <h3 class="mb-0"><a href="#">{{ $announcement->title }}</a></h3>
                                <div class="mb-3">
                                    by <b>{{ $announcement->administrator->name ?? '-' }}</b>
                                </div>
                                <p align="justify">
                                    {{ substr(strip_tags($announcement->description), 0, 200) }}..
                                </p>
                            </div>
                        </div>
                    @endforeach

                    <div class="col-lg-12 mb-5 mt-5 d-flex justify-content-end">
                        <a href="{{ route('home.announcement') }}">
                            <button class="btn btn-primary">Lihat Lebih Banyak</button>
                        </a>
                    </div>
                @else

                    <div class="col-lg-12 text-center">
                        <p>Tidak ada pengumuman untuk saat ini</p>
                    </div>
                @endif
            </div>
        </div>
    </div>

    @guest
        <div class="site-section ftco-subscribe-1" style="background-image: url('{{ asset('home/images/hero_2.jpg') }}')">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <h2>Tunggu Apalagi?</h2>
                        <p>Saatnya sekarang juga anda bergabung menjadi mitra kami.</p>
                    </div>
                    <div class="col-lg-5 d-flex justify-content-end">
                        <a href="/register" class="btn btn-outline-light rounded py-3 px-4" type="submit">Bergabung Menjadi
                            Mitra</a>
                    </div>
                </div>
            </div>
        </div>

    @endguest

@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

	<title>Login Mitra- {{ env("APP_NAME") }}</title>
	<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 11]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="" />
	<meta name="keywords" content="">
	<meta name="author" content="Phoenixcoded" />
	<!-- Favicon icon -->
	<link rel="icon" href="{{ asset('admin/dist/assets/images/favicon.ico') }}" type="image/x-icon">

	<!-- vendor css -->
	<link rel="stylesheet" href="{{ asset('admin/dist/assets/css/style.css') }}">
	
	


</head>

<!-- [ auth-signin ] start -->
<div class="auth-wrapper" style="background: #f8f9fd">
	<div class="auth-content">
		<div class="card">
			<div class="row align-items-center text-center">
				<div class="col-md-12">
					<div class="card-body">
						<a href="{{ route('home.index') }}">
                            <img src="https://banglikab.bps.go.id/backend/images/Header-Frontend-Besar-ind.png" alt="" class="img-fluid mb-4">
                        </a>
						<h4 class="mb-3 f-w-400">Login Mitra</h4>
						<form action="{{ route('admin.login') }}" method="POST">
							@csrf
							<div class="form-group mb-3">
								<label class="floating-label" for="Email">Alamat Email</label>
								<input type="text" class="form-control" name="email" id="Email" placeholder="">
								@error('email')
									<small class="form-text text-danger" style="text-align: left">{{ $message }}</small>
								@enderror
							</div>
							<div class="form-group mb-4">
								<label class="floating-label" for="Password">Kata Sandi</label>
								<input type="password" class="form-control" name="password" id="Password" placeholder="">
								@error('password')
									<small class="form-text text-danger" style="text-align: left">{{ $message }}</small>
								@enderror
							</div>
							<button class="btn btn-block btn-primary mb-4">Login</button>
						</form>
						<p class="mb-0 text-muted">Belum memiliki akun? <a href="{{ route('register.index') }}" class="f-w-400">Daftar</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- [ auth-signin ] end -->

<!-- Required Js -->
<script src="{{ asset('admin/dist/assets/js/vendor-all.min.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/plugins/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/ripple.js') }}"></script>
<script src="{{ asset('admin/dist/assets/js/pcoded.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
	$(document).ready(function(){
		@if(session()->has('success'))
                swal("Success", "{{ session()->get('success') }}", "success");
		@elseif(session()->has('error'))
			swal("Error", "{{ session()->get('error') }}", "error");
		@endif
	})
</script>



</body>

</html>