routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['middleware' => 'auth.administrators'], function () {
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');
        Route::resource('/user/administrator', 'Admin\AdminController');
        Route::resource('/user/partner', 'Admin\PartnerController');
        // Route::post('/user/partner/{id}/destroy', 'Admin\PartnerController@destroy')->name('destroy_partner');

        Route::resource('/vacancy', 'Admin\VacancyController');

        Route::get('/vacancy/{id}/applies', 'Admin\VacancyController@applies')->name('vacancy.applies.index');
        Route::get('/vacancy/{id}/applies/{apply_id}', 'Admin\VacancyController@applies_action')->name('vacancy.applies.action');

        Route::get('/vacancy/{id}/interview', 'Admin\InterviewController@interview')->name('interview');
        Route::post('/store_interview', 'Admin\InterviewController@store_interview')->name('store_interview');

        Route::get('/vacancy/{id}/submit_interview', 'Admin\InterviewController@submit_interview')->name('submit_interview');
        Route::post('/store_submit_interview', 'Admin\InterviewController@store_submit_interview')->name('store_submit_interview');

        Route::resource('/announcement', 'Admin\AnnouncementController');

        Route::resource('/activity', 'Admin\ActivityController');


        Route::resource('/setting', 'Admin\SettingController');
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
            Route::get('/about_us/edit/{id}', 'Admin\SettingController@edit_about_us')->name('edit_about_us');
            Route::post('/about_us/update_about_us/{id}', 'Admin\SettingController@update_about_us')->name('update_about_us');
            Route::get('/about_us/add_about_us', 'Admin\SettingController@create_about_us')->name('create_about_us');
            Route::post('/about_us/store_about_us', 'Admin\SettingController@store_about_us')->name('store_about_us');
        });

        Route::resource('/position', 'Admin\PositionController');
        Route::get('/position/detail/{id}', 'Admin\PositionController@detail_posisi')->name('detail_position');
    });

    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout');
});


Route::get('/pusher', function () {
    return view('welcome2');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

// Login

Route::get('/login', 'Auth\LoginController@login_partner')->name('login.index');
Route::get('/register', 'Auth\RegisterController@register_partner')->name('register.index');
Route::post('/register', 'Auth\RegisterController@register_partner_store')->name('register.store');
Route::get('/logout', 'Auth\LoginController@logout_partner')->name('logout');

Route::post('/upload', 'UploadController@upload')->name('upload');

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/vacancy', 'HomeController@vacancy')->name('vacancy');
    Route::get('/vacancy/{id}', 'HomeController@vacancy_detail')->name('vacancy.detail');
    Route::post('/vacancy/{id}/apply', 'HomeController@vacancy_apply')->name('vacancy.apply');
    Route::get('/announcement', 'HomeController@announcement')->name('announcement');
    Route::get('/announcement/{id}', 'HomeController@announcement_detail')->name('announcement.detail');
    Route::get('/activity', 'HomeController@activity')->name('activity');

    //profile

    Route::get('/account/profile', 'HomeController@profile')->name('profile');
    Route::post('/account/profile', 'HomeController@profile_update')->name('profile.update');

    Route::get('/account/applies', 'HomeController@applies')->name('applies');
    Route::get('/account/applies/{id}/detail', 'HomeController@applies_detail')->name('applies_detail');
    Route::get('/account/applies/{id}/cancel', 'HomeController@applies_cancel')->name('applies.cancel');
});

// Route::get('test_admin', function () {
//     event(new App\Events\NotifAdmin('Lolosneee', 'Didik Ariyana', '1605365067.png', '2020-12-02 19:34:16'));
//     return "Event has been sent!";
// });

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Uuid;

class Vacancy extends Model
{
    protected $table = 'vacancies';

    protected $fillable = [
        'administrator_id',
        'photo',
        'title',
        'description',
        'max_partner',
        'end_period',
        'status'
    ];

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot();

        // Set UUID on boot.
        self::creating(function ($model) {
            $model->id = (string)Uuid::generate(1);
        });
    }

    public function detail()
    {
        return $this->hasMany('App\VacancyDetail');
    }

    public function applies()
    {
        return $this->hasMany('App\VacancyApply');
    }

    public function interview()
    {
        return $this->hasMany('App\Interview');
    }
}

app/Http/Controllers/Admin/VacancyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\DB;

use App\Vacancy;
use Auth;
use App\Position;
use App\VacancyDetail;
use App\VacancyApply;
use App\Partner;
use App\Interview;
use Mail; 

class VacancyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Vacancy::orderBy('created_at','DESC')->get();

        return view('admin.vacancy.index', [
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $positions = Position::orderBy('name', 'ASC')->get();

        return view('admin.vacancy.create',[
            'positions' => $positions
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'end_period' => 'required|date',
            'photo' => 'required|file|mimes:jpeg,jpg,png|max:2048',
            'status' => 'nullable|boolean',
        ]);

        $req = [
            'title' => $request->title,
            'description' => $request->description,
            'end_period' => \Carbon\Carbon::parse($request->end_period),
            'administrator_id' => Auth::guard('administrators')->user()->id
        ];

        if($request->status){
            $req['status'] = "ACTIVE";
        }
        else{
            $req['status'] = "INACTIVE";
        }

        if($request->hasFile('photo')){
            $file = $request->file('photo');
            $file_extension = $file->getClientOriginalExtension();
            $file_name = time() . "." . $file_extension;
            
            try{
                $file->move('uploads/vacancy/', $file_name);
                // $req['photo'] = url("uploads/vacancy/$file_name");
                $req['photo'] = $file_name;
            }
            catch(\Exception $e){
                return redirect()
                        ->back()
                        ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
            }
        }

        DB::beginTransaction();
        try{
            $data = Vacancy::create($req);
            foreach($request->positions as $position){
                VacancyDetail::create([
                    'vacancy_id' => $data->id,
                    'position_id' => $position['id'],
                    'max_partner' => $position['max_partner'],
                    'current_partner' => 0
                ]);
            }
            DB::commit();
        }
        catch(\Exception $e){
            DB::rollback();
            return redirect()
                    ->back()
                    ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
        }

        return redirect()
                    ->back()
                    ->with('success', 'Data Successfully Added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Vacancy::with(['detail', 'detail.position'])->where('id',$id)->firstOrFail();
        $positions = Position::orderBy('name', 'ASC')->get();

        return view('admin.vacancy.edit', [
            'data' => $data,
            'positions' => $positions
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Vacancy::where('id', $id)->firstOrFail();

        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'end_period' => 'required|date',
            'photo' => 'nullable|file|mimes:jpeg,jpg,png|max:2048',
            'status' => 'nullable|boolean'
        ]);

        $req = [
            'title' => $request->title,
            'description' => $request->description,
            'end_period' => \Carbon\Carbon::parse($request->end_period),
            'administrator_id' => Auth::guard('administrators')->user()->id
        ];


        if($request->status){
            $req['status'] = "ACTIVE";
        }
        else{
            $req['status'] = "INACTIVE";
        }

        if($request->hasFile('photo')){
            $file = $request->file('photo');
            $file_extension = $file->getClientOriginalExtension();
            $file_name = time() . "." . $file_extension;
            
            try{
                $file->move('uploads/vacancy/', $file_name);
                // $req['photo'] = url("uploads/vacancy/$file_name");
                $req['photo'] = $file_name;
            }
            catch(\Exception $e){
                return redirect()
                        ->back()
                        ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
            }
        }



        DB::beginTransaction();
        try{
            $data->update($req);
            foreach($request->positions as $position){

                // $cek = VacancyDetail::where('vacancy_id', '=', $data->id)
                // ->where('position_id', '=', $position['id'])->get();


                if(VacancyDetail::where('vacancy_id', $data->id)->where('position_id', $position['id'])->exists()){
                   
                    VacancyDetail::where('vacancy_id', $data->id)->where('position_id', $position['id'])->update([
                        'max_partner' => $position['max_partner']
                    ]);

                }else{
                    VacancyDetail::create([
                        'vacancy_id' => $data->id,
                        'position_id' => $position['id'],
                        'max_partner' => $position['max_partner'],
                        'current_partner' => 0
                    ]);
                }

            }
            DB::commit();
        }
        catch(\Exception $e){
            DB::rollback();
            return redirect()
                    ->back()
                    ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
        }

        return redirect()
                    ->back()
                    ->with('success', 'Data Successfully Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Vacancy::where('id', $id)->first();

        if(!$data){
            return response()->json([
                'success' => false,
                'message' => 'Data not found'
            ]);
        }

        DB::beginTransaction();
        try{

            $data->delete();

            DB::commit();
        }
        catch(\Exception $e){
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }

        return response()->json([
            'success' => true,
            'message' => 'Data successfully deleted'
        ]);
    }

    public function applies(Request $request, $id){
        $data = Vacancy::with(['detail','detail.position', 'applies.position', 'applies.partner'])->where('id', $id)->firstOrFail();

        return view('admin.vacancy.applies.index')->with([
            'data' => $data
        ]);
    }

    public function applies_action(Request $request, $id, $apply_id){
        $data = VacancyApply::where('vacancy_id', $id)->where('id', $apply_id)->firstOrFail();
        $user = Partner::where('id', $data->partner_id)->firstOrFail();

        $penirima=$user->email;

        if($request->action == "approved"){
            $data->update([
                'status' => 'APPROVED'
            ]);

            //Kirim email notifikasi
            // try{
            //     Mail::send('email', ['nama' => $user->name, 'pesan' => 'Selamat anda Lulus tahap Admininstrasi'], function ($message) use ($penirima)
            //     {
            //         $message->subject('Informasi Penerimaan Lowongan - Status Administrasi');
            //         $message->from('info@riskyarya.com', 'BPS Bangli');
            //         $message->to($penirima);
            //     });
                
            //     }
            // catch (Exception $e){
            //     return response (['status' => false,'errors' => $e->getMessage()]);
            // }

             return redirect('admin/vacancy/'.$data->id.'/interview');
        }


        if($request->action == "approved-interview"){
            $data->update([
                'status' => 'APPROVED'
            ]);

            //Kirim email notifikasi
            // try{
            //     Mail::send('email', ['nama' => $user->name, 'pesan' => 'Selamat anda Lulus dalam Lowongan XXXX'], function ($message) use ($penirima)
            //     {
            //         $message->subject('Informasi Penerimaan Lowongan - Status Interview');
            //         $message->from('info@riskyarya.com', 'BPS Bangli');
            //         $message->to($penirima);
            //     });
                
            //     }
            // catch (Exception $e){
            //     return response (['status' => false,'errors' => $e->getMessage()]);
            // }

resources/views/admin/vacancy/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Tambah Lowongan - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Tambah Lowongan</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">User</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.vacancy.index') }}">Lowongan</a></li>
                        <li class="breadcrumb-item"><a href="#!">Tambah Lowongan</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Form Lowongan</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ route('admin.vacancy.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Judul <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="title"
                                        value="{{ old('title') }}" aria-describedby="emailHelp" placeholder="Masukan Judul">
                                    @error('title')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Deksripsi <span class="text-danger">*</span></label>
                                    <textarea name="description" id="ckeditor">{{ old('description') }}</textarea>
                                    @error('description')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>


                                <div class="form-group">
                                    <label for="position">Posisi <span class="text-danger">*</span></label>
                                    <select name="" class="select2" name="positions[]" multiple="multiple" required>
                                        @foreach ($positions as $position)
                                            <option value="{{ $position->id }}" data-name="{{ $position->name }}">
                                                {{ $position->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>

                                <div id="max-partner-group">

                                </div>

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Periode Berakhir <span
                                            class="text-danger">*</span></label>
                                    <input type="date" class="form-control" value="{{ date('Y-m-d', strtotime('+1 day')) }}"
                                        id="exampleInputPassword1" name="end_period" placeholder="End Period">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Status Lowongan</label>

                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="status" value="1" class="custom-control-input"
                                            id="is-active">
                                        <label class="custom-control-label" for="is-active">Aktif</label>
                                        @error('status')
                                            <small class="form-text text-danger">{{ $message }}</small>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Photo Thumbnail <span
                                            class="text-danger">*</span></label>
                                    <input type="file" name="photo" class="dropify" />
                                    @error('photo')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <a href="{{ route('admin.partner.index') }}">
                                    <button type="button" class="btn  btn-secondary">Kembali</button>
                                </a>
                                <button type="submit" class="btn  btn-primary">Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ form-element ] end -->
    </div>
    @push('scripts')
        <script>
            $(document).ready(function() {
                $('.select2').select2({
                    width: '100%'
                }).on('change', function() {
                    let data = ``;
                    let options = [];
                    $("#max-partner-group").html('');

                    var selected = $(this).find('option:selected', this);
                    selected.each(function() {
                        options.push({
                            id: $(this).val(),
                            name: $(this).attr('data-name')
                        })
                    })

                    $.each(options, function(key, val) {

                        data += `
                                                                    <div class="form-group">
                                                                            <label for="exampleInputPassword1">Max Partner for <b>${val.name}</b><span class="text-danger">*</span></label>
                                                                            <input type="hidden" name="positions[${key}][id]" value="${val.id}"/>
                                                                            <input type="number" class="form-control" id="exampleInputPassword1" name="positions[${key}][max_partner]" value="1" min="1" placeholder="Max Partner" >
                                                                            @error('max_partner')
                                                                                                    <small class="form-text text-danger">{{ $message }}</small>
                                                                            @enderror
                                                                        </div>
                                                                `
                    });
                    $("#max-partner-group").html(data)
                })
            })

        </script>
    @endpush
@endsection

resources/views/admin/vacancy/interview.blade.php
@extends('admin.layouts.app')

@section('title')
    Interview - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Tambah Interview</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>

                        <li class="breadcrumb-item"><a href="{{ route('admin.activity.index') }}">Interview</a></li>
                        <li class="breadcrumb-item"><a href="#!"> Interview</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Form Interview</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="/admin/store_interview" method="POST" enctype="multipart/form-data">
                                @csrf
                                <input type="hidden" value="{{ $data->id }}" name="applies_id">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nama <span class="text-danger"></span></label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="name"
                                        value="{{ $partner->name }}" aria-describedby="emailHelp" readonly>
                                    @error('description')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="inputEmail4">Lowongan</label>
                                        <input type="lowongan" class="form-control" id="inputEmail4"
                                            value="{{ $vacancy->title }}" readonly>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="inputPassword4">Posisi</label>
                                        <input type="posisi" class="form-control" id="inputPassword4"
                                            value="{{ $position->name }}" readonly>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputPassword1">Tanggal <span class="text-danger">*</span></label>
                                    <input type="datetime-local" class="form-control date"
                                        value="{{ date('Y-m-d', strtotime('+1 day')) }}" id="exampleInputPassword1"
                                        name="tanggal" placeholder="End Period">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Pewawancara <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="pewawancara"
                                        value="{{ old('pewawancara') }}" aria-describedby="emailHelp"
                                        placeholder="Masukan Nama Pewawancara">
                                    @error('pewawancara')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>

                                <a href="{{ route('admin.activity.index') }}">
                                    <button type="button" class="btn  btn-secondary">Kembali</button>
                                </a>
                                <button type="submit" class="btn  btn-primary">Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ form-element ] end -->
    </div>



@endsection