routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['middleware' => 'auth.administrators'], function () {
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');
        Route::resource('/user/administrator', 'Admin\AdminController');
        Route::resource('/user/partner', 'Admin\PartnerController');
        // Route::post('/user/partner/{id}/destroy', 'Admin\PartnerController@destroy')->name('destroy_partner');

        Route::resource('/vacancy', 'Admin\VacancyController');

        Route::get('/vacancy/{id}/applies', 'Admin\VacancyController@applies')->name('vacancy.applies.index');
        Route::get('/vacancy/{id}/applies/{apply_id}', 'Admin\VacancyController@applies_action')->name('vacancy.applies.action');

        Route::get('/vacancy/{id}/interview', 'Admin\InterviewController@interview')->name('interview');
        Route::post('/store_interview', 'Admin\InterviewController@store_interview')->name('store_interview');

        Route::get('/vacancy/{id}/submit_interview', 'Admin\InterviewController@submit_interview')->name('submit_interview');
        Route::post('/store_submit_interview', 'Admin\InterviewController@store_submit_interview')->name('store_submit_interview');

        Route::resource('/announcement', 'Admin\AnnouncementController');

        Route::resource('/activity', 'Admin\ActivityController');


        Route::resource('/setting', 'Admin\SettingController');
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
            Route::get('/about_us/edit/{id}', 'Admin\SettingController@edit_about_us')->name('edit_about_us');
            Route::post('/about_us/update_about_us/{id}', 'Admin\SettingController@update_about_us')->name('update_about_us');
            Route::get('/about_us/add_about_us', 'Admin\SettingController@create_about_us')->name('create_about_us');
            Route::post('/about_us/store_about_us', 'Admin\SettingController@store_about_us')->name('store_about_us');
        });

        Route::resource('/position', 'Admin\PositionController');
        Route::get('/position/detail/{id}', 'Admin\PositionController@detail_posisi')->name('detail_position');
    });

    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout');
});


Route::get('/pusher', function () {
    return view('welcome2');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

// Login

Route::get('/login', 'Auth\LoginController@login_partner')->name('login.index');
Route::get('/register', 'Auth\RegisterController@register_partner')->name('register.index');
Route::post('/register', 'Auth\RegisterController@register_partner_store')->name('register.store');
Route::get('/logout', 'Auth\LoginController@logout_partner')->name('logout');

Route::post('/upload', 'UploadController@upload')->name('upload');

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/vacancy', 'HomeController@vacancy')->name('vacancy');
    Route::get('/vacancy/{id}', 'HomeController@vacancy_detail')->name('vacancy.detail');
    Route::post('/vacancy/{id}/apply', 'HomeController@vacancy_apply')->name('vacancy.apply');
    Route::get('/announcement', 'HomeController@announcement')->name('announcement');
    Route::get('/announcement/{id}', 'HomeController@announcement_detail')->name('announcement.detail');
    Route::get('/activity', 'HomeController@activity')->name('activity');

    //profile

    Route::get('/account/profile', 'HomeController@profile')->name('profile');
    Route::post('/account/profile', 'HomeController@profile_update')->name('profile.update');

    Route::get('/account/applies', 'HomeController@applies')->name('applies');
    Route::get('/account/applies/{id}/detail', 'HomeController@applies_detail')->name('applies_detail');
    Route::get('/account/applies/{id}/cancel', 'HomeController@applies_cancel')->name('applies.cancel');
});

// Route::get('test_admin', function () {
//     event(new App\Events\NotifAdmin('Lolosneee', 'Didik Ariyana', '1605365067.png', '2020-12-02 19:34:16'));
//     return "Event has been sent!";
// });

app/Administrator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Uuid;

class Administrator extends Authenticatable
{
    use Notifiable;

    protected $table = 'administrators';

    protected $fillable = [
        'name',
        'email',
        'password',
        'photo'
    ];

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot();

        // Set UUID on boot.
        self::creating(function ($model) {
            $model->id = (string)Uuid::generate(1);
        });
    }
}

resources/views/admin/administrator/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Tambah Administrator - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Tambah Administrator</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">User</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.administrator.index') }}">Administrators</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Tambah Data</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h5>Form Administrator</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ route('admin.administrator.store') }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nama <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="name"
                                        value="{{ old('name') }}" aria-describedby="emailHelp" placeholder="Enter Name">
                                    @error('name')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email <span class="text-danger">*</span></label>
                                    <input type="email" class="form-control" id="exampleInputEmail1" name="email"
                                        value="{{ old('email') }}" aria-describedby="emailHelp" placeholder="Enter email">
                                    @error('email')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password <span class="text-danger">*</span></label>
                                    <input type="password" class="form-control" id="exampleInputPassword1" name="password"
                                        placeholder="Password">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password Konfrimasi <span
                                            class="text-danger">*</span></label>
                                    <input type="password" class="form-control" id="exampleInputPassword1"
                                        name="password_confirmation" placeholder="Password">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Foto Profile</label>
                                    <input type="file" name="photo" class="dropify" />
                                    @error('photo')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <a href="{{ route('admin.administrator.index') }}">
                                    <button type="button" class="btn  btn-secondary">Kembali</button>
                                </a>
                                <button type="submit" class="btn  btn-primary">Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ form-element ] end -->
    </div>
@endsection

resources/views/admin/administrator/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Edit Administrator - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Edit Administrator</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">User</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.administrator.index') }}">Administrators</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Edit Data</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <h5>Form Administrator</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form action="{{ route('admin.administrator.update', $data->id) }}" method="POST"
                                enctype="multipart/form-data">

                                @method('PUT')
                                @csrf
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Nama <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" name="name"
                                        value="{{ $data->name }}" aria-describedby="emailHelp" placeholder="Enter Name">
                                    @error('name')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email <span class="text-danger">*</span></label>
                                    <input type="email" class="form-control" id="exampleInputEmail1" name="email"
                                        value="{{ $data->email }}" aria-describedby="emailHelp" placeholder="Enter email">
                                    @error('email')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password</label>
                                    <input type="password" class="form-control" id="exampleInputPassword1" name="password"
                                        placeholder="Password">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password Konfirmasi</label>
                                    <input type="password" class="form-control" id="exampleInputPassword1"
                                        name="password_confirmation" placeholder="Password">
                                    @error('password')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Foto Profile</label>
                                    <input type="file" name="photo" class="dropify"
                                        data-default-file="{{ $data->photo }}" />
                                    @error('photo')
                                        <small class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <a href="{{ route('admin.administrator.index') }}">
                                    <button type="button" class="btn  btn-secondary">Kembali</button>
                                </a>
                                <button type="submit" class="btn  btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ form-element ] end -->
    </div>
@endsection

resources/views/admin/administrator/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Data Administrator - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Data Administrator</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">User</a></li>
                        <li class="breadcrumb-item"><a href="#!">Administrators</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ sample-page ] start -->
        <div class="col-sm-12">
            <div class="card">

                <div class="card-header">
                    <h5>Data Administrator</h5>
                    <div class="card-header-right">
                        <div class="btn-group card-option">
                            <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <i class="feather icon-more-horizontal"></i>
                            </button>
                            <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                                <li class="dropdown-item"><a href="{{ route('admin.administrator.create') }}"><span><i
                                                class="feather icon-plus"></i> Add Data</span></a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table id="datatable" class="table table-striped" style="width: 100%">
                        <thead>
                            <tr>
                                <th>Photo</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Joined At</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $administrator)
                                <tr>
                                    <td><img src="{{ $administrator->photo ?? 'https://medgoldresources.com/wp-content/uploads/2018/02/avatar-placeholder.gif' }}"
                                            alt="{{ $administrator->name }}" width="100"></td>
                                    <td>{{ $administrator->name }}</td>
                                    <td>{{ $administrator->email }}</td>
                                    <td>{{ date('d F Y - H:i:s', strtotime($administrator->created_at)) }}</td>
                                    <td>
                                        @if ($administrator->status == 'ACTIVE')
                                            <span class="badge badge-primary">Aktif</span>
                                        @elseif($administrator->status == "INACTIVE")
                                            <span class="badge badge-secondary">Tidak Aktif</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.administrator.edit', $administrator->id) }}">
                                            <button class="btn btn-primary">Edit</button>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
@endsection