routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::group(['middleware' => 'auth.administrators'], function () {
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('dashboard.index');
        Route::resource('/user/administrator', 'Admin\AdminController');
        Route::resource('/user/partner', 'Admin\PartnerController');
        // Route::post('/user/partner/{id}/destroy', 'Admin\PartnerController@destroy')->name('destroy_partner');

        Route::resource('/vacancy', 'Admin\VacancyController');

        Route::get('/vacancy/{id}/applies', 'Admin\VacancyController@applies')->name('vacancy.applies.index');
        Route::get('/vacancy/{id}/applies/{apply_id}', 'Admin\VacancyController@applies_action')->name('vacancy.applies.action');

        Route::get('/vacancy/{id}/interview', 'Admin\InterviewController@interview')->name('interview');
        Route::post('/store_interview', 'Admin\InterviewController@store_interview')->name('store_interview');

        Route::get('/vacancy/{id}/submit_interview', 'Admin\InterviewController@submit_interview')->name('submit_interview');
        Route::post('/store_submit_interview', 'Admin\InterviewController@store_submit_interview')->name('store_submit_interview');

        Route::resource('/announcement', 'Admin\AnnouncementController');

        Route::resource('/activity', 'Admin\ActivityController');


        Route::resource('/setting', 'Admin\SettingController');
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
            Route::get('/about_us/edit/{id}', 'Admin\SettingController@edit_about_us')->name('edit_about_us');
            Route::post('/about_us/update_about_us/{id}', 'Admin\SettingController@update_about_us')->name('update_about_us');
            Route::get('/about_us/add_about_us', 'Admin\SettingController@create_about_us')->name('create_about_us');
            Route::post('/about_us/store_about_us', 'Admin\SettingController@store_about_us')->name('store_about_us');
        });

        Route::resource('/position', 'Admin\PositionController');
        Route::get('/position/detail/{id}', 'Admin\PositionController@detail_posisi')->name('detail_position');
    });

    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout');
});


Route::get('/pusher', function () {
    return view('welcome2');
});

Route::get('test', function () {
    event(new App\Events\StatusLiked('Someone'));
    return "Event has been sent!";
});

// Login

Route::get('/login', 'Auth\LoginController@login_partner')->name('login.index');
Route::get('/register', 'Auth\RegisterController@register_partner')->name('register.index');
Route::post('/register', 'Auth\RegisterController@register_partner_store')->name('register.store');
Route::get('/logout', 'Auth\LoginController@logout_partner')->name('logout');

Route::post('/upload', 'UploadController@upload')->name('upload');

Route::group(['as' => 'home.'], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/vacancy', 'HomeController@vacancy')->name('vacancy');
    Route::get('/vacancy/{id}', 'HomeController@vacancy_detail')->name('vacancy.detail');
    Route::post('/vacancy/{id}/apply', 'HomeController@vacancy_apply')->name('vacancy.apply');
    Route::get('/announcement', 'HomeController@announcement')->name('announcement');
    Route::get('/announcement/{id}', 'HomeController@announcement_detail')->name('announcement.detail');
    Route::get('/activity', 'HomeController@activity')->name('activity');

    //profile

    Route::get('/account/profile', 'HomeController@profile')->name('profile');
    Route::post('/account/profile', 'HomeController@profile_update')->name('profile.update');

    Route::get('/account/applies', 'HomeController@applies')->name('applies');
    Route::get('/account/applies/{id}/detail', 'HomeController@applies_detail')->name('applies_detail');
    Route::get('/account/applies/{id}/cancel', 'HomeController@applies_cancel')->name('applies.cancel');
});

// Route::get('test_admin', function () {
//     event(new App\Events\NotifAdmin('Lolosneee', 'Didik Ariyana', '1605365067.png', '2020-12-02 19:34:16'));
//     return "Event has been sent!";
// });

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Uuid;

class Setting extends Model
{
    protected $table = 'settings';

    protected $fillable = [
        'id',
        'title',
        'description_short',
        'description_long',
        'photo',
        'type'
    ];

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot();

        // Set UUID on boot.
        self::creating(function ($model) {
            $model->id = (string)Uuid::generate(1);
        });
    }
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Setting;
use App\AboutUs;
use Auth;

use Illuminate\Support\Facades\DB;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $about = Setting::where('type', 'ABOUT_PAGE')->first();
        $about_us = AboutUs::orderBy('created_at', 'DESC')->get();

        return view('admin.setting.edit', [
            'about' => $about,
            'about_us' => $about_us
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->_type == "ABOUT_PAGE") {

            $data = Setting::where('id', $id)->where('type', 'ABOUT_PAGE')->firstOrFail();

            $request->validate([
                'title' => 'required',
                'description_short' => 'required',
                'description_long' => 'required',
                'photo' => 'nullable|file|mimes:jpeg,jpg,png|max:2048',
            ]);

            $req = [
                'title' => $request->title,
                'description_short' => $request->description_short,
                'description_long' => $request->description_long,
            ];

            if ($request->hasFile('photo')) {
                $file = $request->file('photo');
                $file_extension = $file->getClientOriginalExtension();
                $file_name = time() . "." . $file_extension;

                try {
                    $file->move('uploads/setting/about-us/', $file_name);
                    $req['photo'] = url("uploads/setting/about-us/$file_name");
                } catch (\Exception $e) {
                    return redirect()
                        ->back()
                        ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
                }
            }

            DB::beginTransaction();
            try {
                $data->update($req);
                DB::commit();
            } catch (\Exception $e) {
                DB::rollback();
                return redirect()
                    ->back()
                    ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
            }

            return redirect()
                ->back()
                ->with('success', 'Data Successfully Updated!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function edit_about_us($id)
    {
        $data = AboutUs::findOrFail($id);
        return view('admin.setting.about_us.edit', [
            'data' => $data
        ]);
    }

    public function update_about_us(Request $request, $id)
    {
        $data = AboutUs::findOrFail($id);

        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'photo' => 'nullable|file|mimes:jpeg,jpg,png|max:2048',
            'status' => 'nullable|boolean'
        ]);

        $req = [
            'title' => $request->title,
            'description' => $request->description,
            'administrator_id' => Auth::guard('administrators')->user()->id
        ];

        if ($request->status) {
            $req['status'] = "PUBLISHED";
        } else {
            $req['status'] = "UNPUBLISHED";
        }

        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $file_extension = $file->getClientOriginalExtension();
            $file_name = time() . "." . $file_extension;

            try {
                $file->move('uploads/about_us/', $file_name);
                // $req['photo'] = url("uploads/activity/$file_name");
                $req['photo'] = $file_name;
            } catch (\Exception $e) {
                return redirect()
                    ->back()
                    ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
            }
        }

        DB::beginTransaction();
        try {
            $data->update($req);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()
                ->back()
                ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
        }

        return redirect()
            ->back()
            ->with('success', 'Data Successfully Updated!');
    }


    public function create_about_us()
    {
        return view('admin.setting.about_us.create');
    }

    public function store_about_us(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'photo' => 'required|file|mimes:jpeg,jpg,png|max:2048',
            'status' => 'nullable|boolean'
        ]);

        $req = [
            'title' => $request->title,
            'description' => $request->description,
            'administrator_id' => Auth::guard('administrators')->user()->id
        ];

        if ($request->status) {
            $req['status'] = "PUBLISHED";
        } else {
            $req['status'] = "UNPUBLISHED";
        }

        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $file_extension = $file->getClientOriginalExtension();
            $file_name = time() . "." . $file_extension;

            try {
                $file->move('uploads/about_us/', $file_name);
                // $req['photo'] = url("uploads/activity/$file_name");
                $req['photo'] = $file_name;
            } catch (\Exception $e) {
                return redirect()
                    ->back()
                    ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
            }
        }

        DB::beginTransaction();
        try {
            AboutUs::create($req);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()
                ->back()
                ->with('error', "Error on line {$e->getLine()} : {$e->getMessage()}");
        }

        return redirect()
            ->back()
            ->with('success', 'Data Successfully Added!');
    }
}

resources/views/admin/setting/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Setting Page - {{ env('APP_NAME') }}
@endsection

@section('content')
    <!-- [ breadcrumb ] start -->
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">Pengaturan Halaman</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard.index') }}"><i
                                    class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="{{ route('admin.announcement.index') }}">Pengaturan</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- [ breadcrumb ] end -->
    <!-- [ Main Content ] start -->
    <div class="row">
        <!-- [ form-element ] start -->
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5>Form Pengaturan</h5>
                </div>
                <div class="card-body">
                    <div class="row">

                        <div class="col-md-12">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                        aria-controls="home" aria-selected="true">Halaman Profil</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                                        aria-controls="profile" aria-selected="false">Tentang Kami</a>
                                </li>
                                {{-- <li class="nav-item">
                                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                                        aria-controls="contact" aria-selected="false">Exampe Tab 3</a>
                                </li> --}}
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                                    <div class="col-md-12 mt-5">
                                        <form action="{{ route('admin.setting.update', $about->id) }}" method="POST"
                                            enctype="multipart/form-data">
                                            @csrf
                                            @method("PUT")
                                            <input type="hidden" name="_type" value="ABOUT_PAGE">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Judul <span
                                                        class="text-danger">*</span></label>
                                                <input type="text" class="form-control" id="exampleInputEmail1" name="title"
                                                    value="{{ $about->title }}" aria-describedby="emailHelp"
                                                    placeholder="Enter Title">
                                                @error('title')
                                                    <small class="form-text text-danger">{{ $message }}</small>
                                                @enderror

                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Deksripsi Singkat<span
                                                        class="text-danger">*</span></label>
                                                <input type="text" class="form-control" id="exampleInputEmail1"
                                                    name="description_short" value="{{ $about->description_short }}"
                                                    aria-describedby="emailHelp" placeholder="Enter Description Short">
                                                @error('description_short')
                                                    <small class="form-text text-danger">{{ $message }}</small>
                                                @enderror
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Deskripsi Panjang<span
                                                        class="text-danger">*</span></label>
                                                <textarea name="description_long"
                                                    id="ckeditor">{{ $about->description_long }}</textarea>
                                                @error('description_long')
                                                    <small class="form-text text-danger">{{ $message }}</small>
                                                @enderror
                                            </div>

                                            <div class="form-group">
                                                <label for="exampleInputPassword1">Foto Thumbnail <span
                                                        class="text-danger">*</span></label>
                                                <input type="file" name="photo" class="dropify"
                                                    data-default-file="{{ $about->photo }}" />
                                                @error('photo')
                                                    <small class="form-text text-danger">{{ $message }}</small>
                                                @enderror
                                            </div>
                                            <a href="{{ route('admin.dashboard.index') }}">
                                                <button type="button" class="btn  btn-secondary">Back</button>
                                            </a>
                                            <button type="submit" class="btn  btn-primary">Update</button>
                                        </form>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    @php $no=1;@endphp
                                    <div class="card-body">
                                        <a class="btn btn-primary mb-3"
                                            href="{{ route('admin.setting.create_about_us') }}">Tambah Data</a>
                                        <table id="datatable" class="table table-striped table-responsive"
                                            style="width:100%">
                                            <thead>
                                                <tr>
                                                    <th>No</th>
                                                    <th>Thumbnail</th>
                                                    <th>Judul</th>
                                                    <th>Deskripsi</th>
                                                    <th>Status</th>
                                                    <th>Aksi</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($about_us as $about_us)
                                                    <tr>
                                                        <td>{{ $no++ }}</td>
                                                        @isset($about_us->photo)
                                                            <td><img src="{{ asset('/uploads/about_us/' . $about_us->photo) }}"
                                                                    alt=" {{ $about_us->name }}" width="100"></td>
                                                        @else
                                                            <td><img src="https://medgoldresources.com/wp-content/uploads/2018/02/avatar-placeholder.gif"
                                                                    alt="{{ $about_us->name }}" width="100"></td>
                                                        @endisset
                                                        <td>{{ $about_us->title }}</td>
                                                        <td>
                                                            <p
                                                                style="display: -webkit-box;
                                                                                                                                                        -webkit-line-clamp: 2;
                                                                                                                                                        -webkit-box-orient: vertical;
                                                                                                                                                        overflow: hidden;
                                                                                                                                                        text-overflow: ellipsis;
                                                                                                                                                        white-space: nowrap; ">
                                                                {!! $about_us->description ?? '-' !!}
                                                            </p>
                                                        </td>
                                                        <td>
                                                            @if ($about_us->status == 'PUBLISHED')
                                                                <span class="badge badge-primary">Diterbitkan</span>
                                                            @elseif($about_us->status == "UNPUBLISHED")
                                                                <span class="badge badge-secondary">Tidak Diterbitkan</span>
                                                            @endif
                                                        </td>
                                                        <td>
                                                            <a
                                                                href="{{ route('admin.setting.edit_about_us', $about_us->id) }}">
                                                                <button class="btn btn-primary">Edit</button>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ form-element ] end -->
    </div>
@endsection